"""Catálogo Convenio de Gestión 2026 (DBCGESTION_26.ID_*_Web)."""

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict

Kind = Literal["ratio_pct", "ratio_raw", "inverse_pct", "dual_ratio", "rate_10k"]


class IndicatorMeta(TypedDict):
    slug: str
    codigo: str
    nombre: str
    tabla: str
    den_col: str
    num_col: str
    kind: Kind
    umbral: float | None
    meta: float | None
    extras: list[str]
    grupo: str
    bloque: str
    descripcion: NotRequired[str]


def _i(
    slug: str,
    codigo: str,
    nombre: str,
    tabla: str,
    den_col: str,
    num_col: str,
    *,
    kind: Kind = "ratio_pct",
    umbral: float | None = None,
    meta: float | None = None,
    extras: list[str] | None = None,
    bloque: str,
    descripcion: str = "",
) -> IndicatorMeta:
    item: IndicatorMeta = {
        "slug": slug,
        "codigo": codigo,
        "nombre": nombre,
        "tabla": tabla,
        "den_col": den_col,
        "num_col": num_col,
        "kind": kind,
        "umbral": umbral,
        "meta": meta,
        "extras": extras or [],
        "grupo": "Convenio de Gestión 2026",
        "bloque": bloque,
    }
    if descripcion:
        item["descripcion"] = descripcion
    return item


INDICATORS: dict[str, IndicatorMeta] = {
    "cg01": _i(
        "cg01",
        "CG-01",
        "Recuperación de anemia en niños de 12 a 18 meses",
        "ID_01_Web",
        "den",
        "num_recup",
        umbral=40,
        meta=50,
        extras=["num", "num_sup_He", "num_dosaje", "num_t1", "num_T3"],
        bloque="Niñez y nutrición",
        descripcion="Porcentaje de niños con diagnóstico previo de anemia que se recuperan (num_recup / den).",
    ),
    "cg02": _i(
        "cg02",
        "CG-02",
        "Culminación de suplementación preventiva de hierro (6 a 11 meses)",
        "ID_02_Web",
        "den",
        "num",
        umbral=40,
        meta=70,
        extras=["num_term_ta", "num_ctrl_hb", "num_dosaje_fin"],
        bloque="Niñez y nutrición",
    ),
    "cg03": _i(
        "cg03",
        "CG-03",
        "Tamizaje neonatal metabólico",
        "ID_03_Web",
        "den",
        "num",
        bloque="Niñez y nutrición",
    ),
    "cg04": _i(
        "cg04",
        "CG-04",
        "Mejora nutricional en menores de 2 años",
        "ID_04_Web",
        "den",
        "num",
        extras=["num1", "num_2"],
        bloque="Niñez y nutrición",
    ),
    "cg05": _i(
        "cg05",
        "CG-05",
        "Vacunación completa para la edad (24 meses)",
        "ID_05_Web",
        "Denominador",
        "Numerador",
        umbral=70,
        meta=85,
        bloque="Inmunizaciones",
    ),
    "cg06": _i(
        "cg06",
        "CG-06",
        "Vacunación oportuna de BCG y Hepatitis B (recién nacidos)",
        "ID_06_Web",
        "den",
        "num",
        umbral=90,
        meta=95,
        extras=["Vacuna_BCG", "Vacuna_HVB"],
        bloque="Inmunizaciones",
    ),
    "cg07": _i(
        "cg07",
        "CG-07",
        "Tasa de éxito de tratamiento para TB sensible",
        "ID_07_Web",
        "den",
        "num",
        bloque="TB y VIH",
    ),
    "cg08": _i(
        "cg08",
        "CG-08",
        "Contactos de TB con terapia preventiva (TPTB) completa",
        "ID_08_Web",
        "den",
        "num",
        bloque="TB y VIH",
    ),
    "cg09": _i(
        "cg09",
        "CG-09",
        "Terapia preventiva para TB en adultos con VIH en TAR",
        "ID_09_Web",
        "denominador",
        "numerador",
        bloque="TB y VIH",
    ),
    "cg10": _i(
        "cg10",
        "CG-10",
        "Procedimientos estomatológicos preventivos (6 meses a 6 años)",
        "ID_10_Web",
        "Den",
        "Num",
        umbral=10,
        meta=None,
        extras=["HO_CUMPLE", "AN_CUMPLE", "FB_CUMPLE", "PD_CUMPLE", "AS_CUMPLE", "NUM_EOC_2026"],
        bloque="Salud bucal y SSR",
        descripcion="Meta dinámica según carga EOC (odontólogos).",
    ),
    "cg11": _i(
        "cg11",
        "CG-11",
        "Acceso a métodos anticonceptivos modernos",
        "ID_11_Web",
        "Den",
        "Num",
        umbral=20,
        meta=45,
        extras=[
            "DIU",
            "SIU",
            "OralComb",
            "InyTrim",
            "InyMens",
            "Implantes",
            "PreservMasc",
            "PreservFem",
            "Ligadura",
            "Vasectomia",
        ],
        bloque="Salud bucal y SSR",
    ),
    "cg12": _i(
        "cg12",
        "CG-12",
        "Atención prenatal de gestantes referidas por riesgo en el hospital",
        "ID_12_Web",
        "Den",
        "Num",
        umbral=40,
        meta=80,
        bloque="Materno perinatal",
    ),
    "cg13": _i(
        "cg13",
        "CG-13",
        "Paquete preventivo básico en gestantes",
        "ID_13_Web",
        "Den",
        "Num",
        umbral=30,
        meta=60,
        extras=["num_exa", "num_apn", "num_suple"],
        bloque="Materno perinatal",
    ),
    "cg14": _i(
        "cg14",
        "CG-14",
        "Tratamiento oncológico oportuno (≤ 37 días)",
        "ID_14_Web",
        "Denominador",
        "Numerador",
        bloque="Oncología y VPH",
        descripcion="Meta segmentada por grupo de hospital (A–D) según categoría.",
    ),
    "cg15": _i(
        "cg15",
        "CG-15",
        "Mamografía bilateral de tamizaje (40 a 69 años)",
        "ID_15_Web",
        "DENOMINADOR",
        "NUMERADOR",
        bloque="Oncología y VPH",
    ),
    "cg16": _i(
        "cg16",
        "CG-16",
        "Vacunación contra el VPH en niños y niñas de 9 años",
        "ID_16_Web",
        "denominador",
        "numerador",
        umbral=80,
        meta=90,
        bloque="Oncología y VPH",
    ),
    "cg17": _i(
        "cg17",
        "CG-17",
        "Atenciones en medicina de rehabilitación en menores de 5 años",
        "ID_17_Web",
        "Den",
        "Num",
        umbral=25,
        meta=30,
        extras=["Atenciones"],
        bloque="Rehabilitación y salud mental",
        descripcion="Meta regional 30% (Lima Metropolitana 35%).",
    ),
    "cg18": _i(
        "cg18",
        "CG-18",
        "Indicador CG-18",
        "ID_18_Web",
        "den",
        "num",
        bloque="Rehabilitación y salud mental",
        descripcion="Sin fórmula DAX en la guía; se reporta como porcentaje num/den.",
    ),
    "cg19": _i(
        "cg19",
        "CG-19",
        "Paquete de depresión / salud mental",
        "ID_19_Web",
        "DENOMINADOR",
        "NUMERADOR",
        extras=["CUMPLE_03_ATC_SALUD_MENTAL", "CUMPLE_01_ATC_PSICOEDUCACION"],
        bloque="Rehabilitación y salud mental",
        descripcion="Sin fórmula DAX en la guía; se reporta como porcentaje.",
    ),
    "cg20": _i(
        "cg20",
        "CG-20",
        "Porcentaje de resolutividad",
        "ID_20_Web",
        "den",
        "num",
        kind="inverse_pct",
        umbral=5,
        meta=5,
        bloque="Hospitales y gestión",
        descripcion="Desempeño inverso: menor o igual a 5% es cumplimiento 100%.",
    ),
    "cg21": _i(
        "cg21",
        "CG-21",
        "Rendimiento de sala de operaciones (SOP)",
        "ID_21_Web",
        "Den",
        "Num",
        kind="ratio_raw",
        meta=85,
        bloque="Hospitales y gestión",
        descripcion="Cirugías electivas por sala-día. Meta 60 (II-1) o 85 (otros).",
    ),
    "cg22": _i(
        "cg22",
        "CG-22",
        "Porcentaje de cirugías suspendidas",
        "ID_22_Web",
        "total_cirugias_programadas",
        "total_cirugias_suspendidas",
        kind="inverse_pct",
        bloque="Hospitales y gestión",
        descripcion="Desempeño inverso: suspendidas / programadas.",
    ),
    "cg23": _i(
        "cg23",
        "CG-23",
        "Porcentaje de ocupación cama",
        "ID_23_Web",
        "Den_Hosp",
        "Num_Hosp",
        kind="dual_ratio",
        umbral=80,
        meta=80,
        extras=["Den_UCI", "Num_UCI"],
        bloque="Hospitales y gestión",
        descripcion="Hospitalización ≥ 80% y UCI ≥ 90%.",
    ),
    "cg24": _i(
        "cg24",
        "CG-24",
        "Intervalo de sustitución cama",
        "ID_24_Web",
        "Den",
        "Num",
        kind="ratio_raw",
        umbral=0,
        meta=2,
        extras=["Dias_Renoxi"],
        bloque="Hospitales y gestión",
        descripcion="Días promedio que una cama permanece libre (esperado 0 a 2).",
    ),
    "cg25": _i(
        "cg25",
        "CG-25",
        "Promedio de espera en consulta externa de pacientes referidos",
        "ID_25_Web",
        "den",
        "num",
        kind="ratio_raw",
        bloque="Hospitales y gestión",
        descripcion="Días de espera. Meta según categoría (I-4=20, II=35, III=45, III-E=22).",
    ),
    "cg26": _i(
        "cg26",
        "CG-26",
        "Utilización de consultorios externos de medicina",
        "ID_26_Web",
        "DENOMINADOR_CONSULTORIO_FISICO",
        "NUMERADOR_CONSULTORIO_FUNCIONAL",
        kind="ratio_raw",
        umbral=2,
        meta=2,
        bloque="Hospitales y gestión",
        descripcion="Turnos por consultorio físico; esperado ≥ 2.",
    ),
    "cg32": _i(
        "cg32",
        "CG-32",
        "Implementación de telemedicina",
        "ID_32_Web",
        "den",
        "Num_Pond",
        kind="rate_10k",
        umbral=10,
        meta=100,
        extras=["TeleInterconsultas", "teleconsultas", "telemonitoreos", "num"],
        bloque="Telemedicina",
        descripcion="Tasa ponderada por 10 000 habitantes (Num_Pond / den × 10 000).",
    ),
}


def list_indicators() -> list[dict[str, Any]]:
    return [
        {
            "slug": m["slug"],
            "codigo": m["codigo"],
            "nombre": m["nombre"],
            "grupo": m["grupo"],
            "bloque": m["bloque"],
            "meta_pct": m["meta"] if m["meta"] is not None else 0,
            "umbral": m["umbral"],
            "kind": m["kind"],
            "patron": "cg-standard",
            "descripcion": m.get("descripcion", ""),
        }
        for m in INDICATORS.values()
    ]


def get_indicator(slug: str) -> IndicatorMeta | None:
    return INDICATORS.get(slug)
